/*
 * Billing Backend
 *
 * # API for managing billing of customers  The purpose of this API is to manage customers, articles, recurring billing, and payments.  The caller has to be authenticated with the system and provide a JWT token in the Authorization header of the HTTP request. When using the API you typically get this token by authenticating first with OAuth 2.0.  When you are trying this API using the Swagger interface, you need to click the `Authorize` button and then again the Authorize button in the pop-up that gets opened.
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DetailedInvoice {
    #[serde(rename = "basic")]
    pub basic: Box<crate::models::Invoice>,
    #[serde(rename = "positions")]
    pub positions: Vec<crate::models::InvoicePosition>,
}

impl DetailedInvoice {
    pub fn new(basic: crate::models::Invoice, positions: Vec<crate::models::InvoicePosition>) -> DetailedInvoice {
        DetailedInvoice {
            basic: Box::new(basic),
            positions,
        }
    }
}


