/*
 * Billing Backend
 *
 * # API for managing billing of customers  The purpose of this API is to manage customers, articles, recurring billing, and payments.  The caller has to be authenticated with the system and provide a JWT token in the Authorization header of the HTTP request. When using the API you typically get this token by authenticating first with OAuth 2.0.  When you are trying this API using the Swagger interface, you need to click the `Authorize` button and then again the Authorize button in the pop-up that gets opened.
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NewInvoice {
    #[serde(rename = "numberGroup")]
    pub number_group: String,
    #[serde(rename = "invoiceNumber", skip_serializing_if = "Option::is_none")]
    pub invoice_number: Option<i32>,
    #[serde(rename = "invoiceDate", skip_serializing_if = "Option::is_none")]
    pub invoice_date: Option<String>,
    #[serde(rename = "dueDate", skip_serializing_if = "Option::is_none")]
    pub due_date: Option<String>,
    #[serde(rename = "customerId")]
    pub customer_id: String,
    #[serde(rename = "currencyId")]
    pub currency_id: String,
}

impl NewInvoice {
    pub fn new(number_group: String, customer_id: String, currency_id: String) -> NewInvoice {
        NewInvoice {
            number_group,
            invoice_number: None,
            invoice_date: None,
            due_date: None,
            customer_id,
            currency_id,
        }
    }
}


